### ISSUE TITLE
Unable to Build - List of languages empty.

### ISSUE THREAD

**Issue by rajeshksv** [bil-elmoussaoui/nautilus-git#1]
Hi, 

While building, I am facing the following error. Can you suggest how to fix it ?

➜  build git:(master) meson .. --prefix /usr               
The Meson build system
Version: 0.34.0
Source dir: /home/mac/nautilus-git
Build dir: /home/mac/nautilus-git/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: nautilus-git
Native c compiler: cc (gcc 6.2.0-5ubuntu12)
Program python2 found: YES (/usr/bin/python2)
Program intltool-merge found: YES (/usr/bin/intltool-merge)
Message: Looking for dependencies
Program python2 found: YES (/usr/bin/python2)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.50.2
Native dependency gobject-2.0 found: YES 2.50.2
Native dependency gobject-introspection-1.0 found: YES 1.50.0
Native dependency gtk+-3.0 found: YES 3.20.9
Message: DESTINATION DIR : /usr
Message: Update translations

Meson encountered an error in file po/meson.build, line 10, column 5:
List of languages empty.

**Comment by bilelmoussaoui** [comment]
@rajeshksv Should be fixed on master

**Comment by bilelmoussaoui** [comment]
Please repoen if you still have this issue :)

**Comment by rajeshksv** [comment]
Yes the error is fixed :) Done with installation. But I don't see any git info in nautilus. I rebooted the system as well. I am using Ubuntu 16.10 Gnome shell 3.20.4.

When I do nautilus -q it says

Gtk-Message: Failed to load module "$GTK3_MODULES"
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.

Is it to do anything ? I can see git.py in /usr4/share/nautilus-python/extensions

**Comment by bilelmoussaoui** [comment]
Both of your error messages has nothing to do with my extension. Can you remove build folder and rebuild from scratch and copy paste all outputs for each step please ?

**Comment by bil-elmoussaoui** [comment]
Both of your error messages has nothing to do with my extension. Can you remove build folder and rebuild from scratch and copy paste all outputs for each step please ?

**Comment by rajeshksv** [comment]
Removed build folder and tried installing again. And it works :+1: May be the build failed due to above bug and then some **** happened. Anyways its working now. Now I wonder how come this plugin functionality isn't default functionality of nautilus in first place ;) Thanks!

**Comment by bilelmoussaoui** [comment]
@rajeshksv You're welcome 👍
