### ISSUE TITLE
Fedora COPR package is broken

### ISSUE THREAD

**Issue by dralley** [bil-elmoussaoui/nautilus-git#11]
At least with Fedora 25, I have not tried other versions.  It also does not appropriately declare nautilus-python a dependency.  Even after installing this it does not work however.

**Comment by bilelmoussaoui** [comment]
Sorry, but i'm not the package maintainer of the Fedora COPR package. So i can't fix it.
When you run those from terminal what happens?
```
nautilus -q
nautilus 
```
Please paste the output here. Thanks!

**Comment by bilelmoussaoui** [comment]
@HeikoAdams Any idea about the COPR package? Sorry for the ping :)

**Comment by dralley** [comment]
@bil-elmoussaoui There's no output

**Comment by HeikoAdams** [comment]
nautilus-python **is** declared as a dependency for tilix-nautilus:

```
%package nautilus
Summary:        %{name} Nautilus integration
Group:          Applications/System
Requires:       nautilus-extensions
Requires:       nautilus-python
Requires:       %{name} = %{version}-%{release}
Obsoletes:	terminix-nautilus <= %{version}-%{release}
```

**Comment by dralley** [comment]
@HeikoAdams But not nautilus-git.  My problem has nothing to do with tilix-nautilus.

nautilus-git.spec:
```
...
BuildRequires:  pkgconfig(gobject-introspection-1.0)

Requires:       nautilus
BuildArch:      noarch
...
```

**Comment by dralley** [comment]
@bil-elmoussaoui I installed from source and it seems to work fine, so it's just the COPR.  You can close the issue if you like.

**Comment by bilelmoussaoui** [comment]
@dralley Thanks! I will close this and hope @HeikoAdams will fix it pretty soon :+1:
