### ISSUE TITLE
Git info bar is higher than other nautilus info bars

### ISSUE THREAD

**Issue by jp7677** [bil-elmoussaoui/nautilus-git#15]
Hi there,
Thanks for this cool nautilus extension. On my system the git bar is slightly higher than other nautilus bars. Would be cool if the height would be somewhat less to match the other info bars. See screenshot for what I mean.
![screenshot from 2017-04-22 16-30-06](https://cloud.githubusercontent.com/assets/17219293/25305318/641a9436-2779-11e7-8475-351062b805f7.png)

Regards,
jens

**Comment by bilelmoussaoui** [comment]
I will take care of that :) Thanks for reporting !

**Comment by bilelmoussaoui** [comment]
Can you compare the Info bar of the trash folder? The info bar on templates folder doesn't contain any Gtk.Button, which is the reason why it looks much more smaller then the git one

**Comment by jp7677** [comment]
Ah ok, yes, the trash info bar is indeed also much higher than the templates bar, though still some pixels smaller than the git bar.
![screenshot from 2017-04-23 10-21-40](https://cloud.githubusercontent.com/assets/17219293/25312045/e9b51c20-280e-11e7-8f4c-4483d6aba948.png)

![screenshot from 2017-04-23 10-24-34](https://cloud.githubusercontent.com/assets/17219293/25312049/13bfb98a-280f-11e7-9223-30bd2f105677.png)

I would prefer to have both the same size of the templates bar, but that seems more a theming issue and not something within your extension.

**Comment by jp7677** [comment]
Feel free to close this issue if you want to keep it like it is, I can certainly very well become used to the current appearance ;)

**Comment by bilelmoussaoui** [comment]
Sorry for the long delay, i tried to reduce it's size but it's not possible due to the use of a Gtk.Button :+1:
