### ISSUE TITLE
Choose Branch Menu Always in center of screen.

### ISSUE THREAD

**Issue by worldofpeace** [bil-elmoussaoui/nautilus-git#16]
OS: Arch Linux
Installed From: AUR
nautilus-git version: 1.2

When I click the current branch GtkButton that opens the window to switch the branch, it is always at the center of the screen.
![screenshot from 2017-05-29 17-55-59](https://cloud.githubusercontent.com/assets/28888242/26562845/3b178026-4498-11e7-8e12-175833fe9445.png)

The correct behaviour would be for the window to appear in the center of the NautilusWindow.

**Comment by bilelmoussaoui** [comment]
Fixed on master
