### ISSUE TITLE
ninja install failing (msgfmt ITS rules issue)

### ISSUE THREAD

**Issue by phocean** [bil-elmoussaoui/nautilus-git#25]
Hi,

I am on openSUSE Tumbleweed, so I am installing from source.

It fails on:

```
% sudo ninja -C builddir install                      
ninja: Entering directory `builddir'
[1/2] 'Generating nautilus-git.metainfo.xml_merge with a custom command.'
FAILED: data/nautilus-git.metainfo.xml 
'msgfmt' '--xml' '--template' '../data/nautilus-git.metainfo.xml.in' '-d' '../data/../po' '-o' 'data/nautilus-git.metainfo.xml'
msgfmt: Impossible de localiser les règles ITS pour ../data/nautilus-git.metainfo.xml.in
ninja: build stopped: subcommand failed.
```

The message is cryptic to me, sorry.

**Comment by bilelmoussaoui** [comment]
As i'm not an expert with gettext and all the translations stuff, i will redirect you to this issue https://github.com/mesonbuild/meson/issues/1565
it seems that you have some missing its files.

**Comment by TingPing** [comment]
Have `gettext >= 0.19.6` and have the dev package for `libappstream-glib` installed.

**Comment by phocean** [comment]
Thank you. But I have libappstream-glib8 and gettext version 0.19.8.1 (tumbleweed is very up-to-date as it is the rolling release).

Here is what I have in the its folder:

```
% ls /usr/share/gettext/its
gschema.its  gschema.loc  gtkbuilder.its  gtkbuilder.loc
```

Do you have more files ?

**Comment by bilelmoussaoui** [comment]
@phocean Yep
```
ls /usr/share/gettext/its/                                                     
appdata.its  gnome-keybindings.its  gschema.its  gtkbuilder.its  polkit.its
appdata.loc  gnome-keybindings.loc  gschema.loc  gtkbuilder.loc  polkit.loc
```

**Comment by TingPing** [comment]
> But I have libappstream-glib8 

I specifically said the dev package because most distros split the itstool files out.

**Comment by phocean** [comment]
Hmm, it seems I am doomed.
For instance:

`% zypper search --provides --match-exact "/usr/share/gettext/its/appdata.its"`

returns nothing.

And the distribution does not seem to have a libappstream-glib8 devel package. I will try to get the info from an openSUSE source...

**Comment by bilelmoussaoui** [comment]
@phocean I've never used openSUSE before, I can't help you with that. Anyway, if you find which package was missing can you write a comment here with the package name? for future openSUSE users.
Closing

**Comment by TingPing** [comment]
Many GNOME projects have been moving from `intltool` to `gettext` this past year, so I'm not sure it makes sense to not be packaged.

**Comment by phocean** [comment]
Hi, problem solved with installing `appstream-glib-devel`.

I don't know why I missed this package the other time, probably got confused by the naming.
Thank you for the hints and keep up the good work ;-)

**Comment by eexpress** [comment]
> Have `gettext >= 0.19.6` and have the dev package for `libappstream-glib` installed.

`dnf install libappstream-glib-devel`. I think you need add this into README. :D

**Comment by bilelmoussaoui** [comment]
@eexpress mind sending a PR?

**Comment by archisman-panigrahi** [comment]
In Ubuntu 20.04, installing the package `appstream` solved a [similar issue](https://askubuntu.com/questions/1273027/debian-package-builds-in-my-computer-but-fails-to-build-in-launchpad-and-pbuild).

`libappstream-glib-dev` did not work in Ubuntu.
