### ISSUE TITLE
Build prefix

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#3]
• Isn't it possible to work with regular build prefix "/usr/local/"? I tried and it sadly didn't work.
• If it's required to specify the "/usr" prefix, could you add this please to the Meson config? Otherwise people just run `meson ..` and wonder why it doesn't work… until they read the README file.

**Comment by bilelmoussaoui** [comment]
@fbruetting I'm going to try to build it on all possible distros out there to avoid users building the package by themselves.  Anyway, the installation method to follow is here : https://github.com/bil-elmoussaoui/nautilus-git#how-to-install
The extension should work perfectly if installed under `$HOME/.local/` as a prefix too! It's must be an upstream issue for Nautilus for not detecting extensions installed under `/usr/local/share/nautilus-python/extensions/`
I will mark this as invalid, as i already give the installation instruction on the README!

**Comment by fbruetting** [comment]
Ok, maybe this is one of my many Fedora issues then, I'll test again in some weeks…

**Comment by bilelmoussaoui** [comment]
Please report back once you've tested it! So i will either open an issue upstream or mention that on the readme.
