### ISSUE TITLE
last meson usage update broke aur package 

### ISSUE THREAD

**Issue by CircleCode** [bil-elmoussaoui/nautilus-git#30]
it seems meson builds `/usr/share/icons/hicolor/icon-theme.cache` again, preventing installation (see https://aur.archlinux.org/packages/nautilus-ext-git/)

**Comment by bilelmoussaoui** [comment]
I will see what can i do as soon as possible :)

**Comment by bilelmoussaoui** [comment]
I've just pushed a fix to the AUR repository. Should be fixed now

**Comment by CircleCode** [comment]
I confirm this is fixed, thanks
