### ISSUE TITLE
Question: how do I get compare (diff) window?

### ISSUE THREAD

**Issue by luca-viggiani** [bil-elmoussaoui/nautilus-git#39]
I've istalled from AUR nautilus-ext-git,
The extension works fine and shows me the changed files list when I click on the pencil icon on top yellow bar. However if I select one of the files from the popup menu, nothing happens (I expect to have the compare window like the second screenshot in the README.md file).

Do I miss any (optional) dependency?
Thanks!

**Comment by luca-viggiani** [comment]
...ok sorry... it's in "more.." menu... :(

**Comment by bilelmoussaoui** [comment]
Glad you figured it out :+1:
