### ISSUE TITLE
HiDPI scaling

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#4]
Here's a screenshot on my UHD screen, would you correct the icon scaling please? (But I must admit, that Fedora has several UI bugs recently, so I'm not sure if this is due to Fedora or your program).

![bildschirmfoto vom 2017-02-11 20-15-17](https://cloud.githubusercontent.com/assets/10520767/22856686/d63ea4ea-f096-11e6-9865-f98356aa0948.png)

**Comment by bilelmoussaoui** [comment]
Well, I don't hardcode the icon size at all. I'm using Gtk.IconSize.SMALL_TOOLBAR (=16px) https://github.com/bil-elmoussaoui/nautilus-git/blob/master/nautilus-git/git.py#L138
I think that it's an upstream issue... Anyway, i don't have a UHD screen to test it, but it would be really cool if you can try it with an other distro(Archlinux ?)

**Comment by fbruetting** [comment]
I can spin up a Debian VM, is this ok?

**Comment by bilelmoussaoui** [comment]
@fbruetting Perfect ! 👍

**Comment by fbruetting** [comment]
Ok, this "missing icon" icon is not scaled, but the Git icon is (after your work on refreshing the icon cache). So everything's fine.

**Comment by bilelmoussaoui** [comment]
Awesome 👍
