### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by davidovitch** [bil-elmoussaoui/nautilus-git#42]
Support for Python3 would be nice at some point (https://pythonclock.org/). I don't know about other distributions, but at least on Arch Linux you can chose between `python2-nautilus` or `python-nautilus` for the Python bindings.

A quick test on my Arch Linux system showed that `2to3` creates a version of the current master that works just like that with `python-nautilus`. I am sure you can make the code 2 and 3 compatible at the same time, but that usually requires a little extra work. I can help out with a PR if needed.

**Comment by MaxSchambach** [comment]
I felt the same way, see my PR #45 :)

**Comment by bilelmoussaoui** [comment]
Fixed on master thanks to @MaxSchambach
