### ISSUE TITLE
No items

### ISSUE THREAD

**Issue by webmastak** [bil-elmoussaoui/nautilus-git#48]
No items. Streaked on the screenshot. How to activate them?

[![https://i.imgur.com/ruuT6tD.jpg](https://i.imgur.com/ruuT6tD.jpg)](https://i.imgur.com/ruuT6tD.jpg)
```
nautilus 3.30
python2-nautilus 1.2.2-3
nautilus-git 1.3-1
git version 2.21.0
```

**Comment by bilelmoussaoui** [comment]
You can't active those, it just give you an indicator of how many files you have changed on the current git repository.

**Comment by webmastak** [comment]
**SOLVED, subject can be closed.**

In file: `/usr/share/nautilus-git/src/models/git.py`
Because of the Russian localization of the command, grep was empty.

```
        modified = execute("git status | grep 'modified:'", self.dir)
        removed = execute("git status | grep 'deleted:'", self.dir)
        added = execute("git status | grep 'new file:'", self.dir)
```

Replaced with this and everything worked as it should.
```
        modified = utils.execute("git status | grep 'изменено:'", self.dir)
        removed = utils.execute("git status | grep 'удалено:'", self.dir)
        added = utils.execute("git status | grep 'новый файл:'", self.dir)
```
