### ISSUE TITLE
Support of local repositories

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#5]
Hi again, your nice script doesn't work with local repositories. Would you like to support this, too?

**Comment by bilelmoussaoui** [comment]
@fbruetting What do you mean by local repos?

**Comment by fbruetting** [comment]
Git repos, which aren't on GitHub, like this one:
![bildschirmfoto vom 2017-02-12 14-56-39](https://cloud.githubusercontent.com/assets/10520767/22862666/7cc3ae7c-f133-11e6-8b0b-0b75b21c9bfc.png)

I only see your added top bar on projects I cloned from GitHub, but on none of my own local projects.

**Comment by bilelmoussaoui** [comment]
@fbruetting From where did you get this repo? I've tried it even with Archlinux AUR packages (git and it works 
![screenshot from 2017-02-12 15-01-12](https://cloud.githubusercontent.com/assets/7660997/22862709/1d232ec4-f134-11e6-88f4-13fc8ecb559e.png)

**Comment by fbruetting** [comment]
I created it by myself via `git init`…?

**Comment by bilelmoussaoui** [comment]
Fixed on master :-)

**Comment by bilelmoussaoui** [comment]
@fbruetting My bad, this wasn't fixed correctly :P now it's the case :)
![screenshot from 2017-02-12 15-29-59](https://cloud.githubusercontent.com/assets/7660997/22862928/21e81e0c-f138-11e6-9056-81c74a56938f.png)

**Comment by fbruetting** [comment]
Thanks, I tested it and it works (twice, but saw no difference :P). But now the Git icon now is missing, while it was there yesterday… [Installing Debian in a VM right now].

**Comment by bilelmoussaoui** [comment]
@fbruetting nothing changed in that part of code :o when you run Nautilus from terminal do you have any error message?

**Comment by fbruetting** [comment]
Just the usual stuff:
```
$ nautilus
(nautilus:13720): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
(nautilus:13720): GLib-GIO-CRITICAL **: g_dbus_interface_skeleton_unexport: assertion 'interface_->priv->connections != NULL' failed
```

But Fedora fucks up constantly in the last time, maybe it's an issue due to this:
![bildschirmfoto vom 2017-02-12 15-39-30](https://cloud.githubusercontent.com/assets/10520767/22863019/76d39986-f139-11e6-89b2-b78a7ea23652.png)

**Comment by bilelmoussaoui** [comment]
Kill nautilus first, `nautilus -q` and restart it

**Comment by fbruetting** [comment]
Ok, I actually did both `killall nautilus` and `nautilus -q`, but maybe in the wrong order:
```
$ nautilus -q
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Initializing nautilus-dropbox 2015.10.28

$ nautilus
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Initializing nautilus-dropbox 2015.10.28
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
```
Now the icon sizes are half size… (but get restored to normal size by Ctrl+R):
![bildschirmfoto vom 2017-02-12 15-44-37](https://cloud.githubusercontent.com/assets/10520767/22863057/2ba181d4-f13a-11e6-8fa0-0e3299f85b0c.png)

Git icon still missing…

**Comment by bilelmoussaoui** [comment]
No error message will be shown until you're on a git directory. Can you try that? maybe the icon is not loaded correctly. And by the way, i might know why :P I forgot to add a icon theme cache refresh :P

**Comment by fbruetting** [comment]
No, no error:
```
Handling file:  file:///home/frank/Informatik/Git/FeedReader
file scheme:  file
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Handling file:  file:///home/frank/Informatik/Git/FeedReader
file scheme:  file
Handling file:  file:///home/frank/Informatik/Git/nautilus-git
file scheme:  file
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Number of files is 0
Handling file:  file:///home/frank/Informatik/Git/nautilus-git
file scheme:  file
Number of files is 0
```

The icon is stored at `/usr/share/icons/hicolor/scalable/status/nautilus-git-symbolic.svg` at my system.

**Comment by bilelmoussaoui** [comment]
@fbruetting I've added refreshing the icon cache on my latest commit in order to fix this (if it's due to that?)
Have you changed your icon theme? If, so can you paste the content of the index.theme under the theme directory?

**Comment by fbruetting** [comment]
YES, works again, thanks!

**Comment by bilelmoussaoui** [comment]
Perfect, happy to hear that :)
