### ISSUE TITLE
Theming support

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#6]
Big sorry for flooding, but as you see in the screenshots, the Adapta theme highlights all additional appearing top bars in nautilus yellow, but not your top bar. I don't know if it'll be appropriate for your script, and I even don't really know how this works internally, but if you want to have theming support, I think you need to implement those hintings.

![bildschirmfoto vom 2017-02-11 20-21-25](https://cloud.githubusercontent.com/assets/10520767/22856716/bc911144-f097-11e6-9518-f9f6c40a9815.png)

![bildschirmfoto vom 2017-02-11 20-29-40](https://cloud.githubusercontent.com/assets/10520767/22856782/d944fee4-f098-11e6-893d-7d1575867bf1.png)

**Comment by bilelmoussaoui** [comment]
I'm not using any specific CSS theming; i'm just using an InfoBar widget with the type OTHER as you can see here https://github.com/bil-elmoussaoui/nautilus-git/blob/master/nautilus-git/git.py#L126 
The  Yellow color in Adapata is for the type "QUESTION". Which isn't the type of the information shown by this extension. So, i can't really do anything about it...

**Comment by fbruetting** [comment]
Ok, I thought it was a general highlighting, sorry!

**Comment by bilelmoussaoui** [comment]
Anyway, it seems that Nautilus use it everywhere even in the template folder instead of using OTHER as a message type :P 
You can change that manually pretty easily, and it won't really disturb me to change it to QUESTION type if it will look good with other themes too :)

**Comment by bilelmoussaoui** [comment]
It seems that Adwaita does not provide any theming for OTHER type of InfoBar message, i will switch to Question as it's used everywhere :)

**Comment by bilelmoussaoui** [comment]
Fixed
