### ISSUE TITLE
Build and destribute

### ISSUE THREAD

**Issue by bilelmoussaoui** [bil-elmoussaoui/nautilus-git#7]
- [x] Archlinux (will do it)
- [x] Fedora
- [x] Ubuntu/Debian

**Comment by HeikoAdams** [comment]
Fedora Packages are in progress: https://copr.fedorainfracloud.org/coprs/heikoada/nautilus-git/

**Comment by bilelmoussaoui** [comment]
@HeikoAdams Thanks! Please create a PR with the installation instruction on README file  once it's ready 👍

**Comment by bilelmoussaoui** [comment]
@HeikoAdams Any news? 
@khurshid-alam Do you have some free time to take care of the PPA packaging? That would be really awesome!

**Comment by HeikoAdams** [comment]
@bil-elmoussaoui yes. Packages are built and copr is ready for usage. Sorry, but I was very busy last days.

**Comment by bilelmoussaoui** [comment]
@HeikoAdams Thanks! I've added the installation method on the README! Please feel free to update it or modify whatever you want :)

**Comment by khurshid-alam** [comment]
@bil-elmoussaoui Yes. Right now I am very busy. I will take a look this weekend. BTW what should be the package version? 0.1?

**Comment by bilelmoussaoui** [comment]
I will release a version on Github to make it easier for you :) but should be 0.1! And take your time

**Comment by bilelmoussaoui** [comment]
@khurshid-alam I've created a new release (v1.0)

**Comment by khurshid-alam** [comment]
PPA is already available under: https://launchpad.net/~khurshid-alam/+archive/ubuntu/nautilus-git

I will change the version soon.

**Comment by bilelmoussaoui** [comment]
Thank you guys! This is done 👍

**Comment by bilelmoussaoui** [comment]
@khurshid-alam @HeikoAdams I've released a new version (1.2)! Can you please update the packages? Than you very much!

**Comment by khurshid-alam** [comment]
@bil-elmoussaoui Done!

**Comment by bilelmoussaoui** [comment]
Hey guys, i've just released a new version which adds nemo support! You will have to create a new package for it.
Just take a look at the readme, i explained how to build for Nemo/Nautilus, build system by default uses Nautilus. 

Thank you very much!

**Comment by khurshid-alam** [comment]
@bil-elmoussaoui  Debhelper doesn't support meson properly yet. So the latest commit made the PPA broken for all older Ubuntu versions.
