### ISSUE TITLE
Missing remove/uninstall target

### ISSUE THREAD

**Issue by fbruetting** [bil-elmoussaoui/nautilus-git#9]
There's no way for uninstalling the installed files, would you add such a target please?

**Comment by bilelmoussaoui** [comment]
@fbruetting ofc! i will do that as soon as possible :)

**Comment by bilelmoussaoui** [comment]
Meson provides a way to remove the installed files using meson uninstall. But that does not work quite correctly if you have already removed the files under build folder. I think i will add a simple bash script that removes the git.py file and the nautilus-git-symbolic icon... i will have to think about it :p

**Comment by fbruetting** [comment]
Ah, i tried `ninja uninstall` and `ninja remove`, because ninja also installed the files. But `meson uninstall` sadly doesn't work.

**Comment by bilelmoussaoui** [comment]
I'm back, sorry for the delay! i have been busy with RL :) I think the best way to handle this is to package nautilus-git correctly instead of compiling from source code... 
I will anyway provide a bash script to remove it :)

**Comment by bilelmoussaoui** [comment]
Done! https://github.com/bil-elmoussaoui/nautilus-git#how-to-uninstall
